### ISSUE TITLE
Der Test-Server verschickt keine Mails, javax.mail.MessagingException: Could not convert socket to TLS

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/yopenedi#194]
1. Im Log sehe ich das folgende
2. <img width="937" alt="Bildschirmfoto 2021-05-03 um 10 46 17" src="https://user-images.githubusercontent.com/4953/116857309-de065f80-abfc-11eb-9411-0b85b5983e7f.png">
3. Aber im Mail-Account sehe ich nichts.
4. ![Bildschirmfoto 2021-05-03 um 10 47 35](https://user-images.githubusercontent.com/4953/116857375-fbd3c480-abfc-11eb-8ebd-8a03e8ea99a3.png)

**Comment by zdavatz** [comment]
Das ist der Error im Log
```

2021-05-03 20:40:35.084950500 javax.mail.MessagingException: Could not convert socket to TLS;
2021-05-03 20:40:35.084952500   nested exception is:
2021-05-03 20:40:35.084952500 	javax.net.ssl.SSLHandshakeException: No appropriate protocol (protocol is disabled or cipher suites are inappropriate)
2021-05-03 20:40:35.085949500 javax.mail.MessagingException: Could not convert socket to TLS;
2021-05-03 20:40:35.085949500   nested exception is:
2021-05-03 20:40:35.085949500 	javax.net.ssl.SSLHandshakeException: No appropriate protocol (protocol is disabled or cipher suites are inappropriate)
2021-05-03 20:40:35.086137500 	at com.sun.mail.smtp.SMTPTransport.startTLS(SMTPTransport.java:1907)
2021-05-03 20:40:35.086165500 	at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:666)
2021-05-03 20:40:35.086190500 	at javax.mail.Service.connect(Service.java:317)
2021-05-03 20:40:35.086218500 	at javax.mail.Service.connect(Service.java:176)
2021-05-03 20:40:35.086241500 	at javax.mail.Service.connect(Service.java:125)
2021-05-03 20:40:35.086265500 	at javax.mail.Transport.send0(Transport.java:253)
2021-05-03 20:40:35.086288500 	at javax.mail.Transport.send(Transport.java:124)
2021-05-03 20:40:35.086313500 	at com.ywesee.java.yopenedi.common.ResultDispatch.sendEmail(ResultDispatch.java:180)
2021-05-03 20:40:35.086336500 	at com.ywesee.java.yopenedi.common.ResultDispatch.send(ResultDispatch.java:117)
2021-05-03 20:40:35.086363500 	at com.ywesee.java.yopenedi.common.Config.dispatchResult(Config.java:103)
2021-05-03 20:40:35.086387500 	at controllers.HomeController.janicoFn(HomeController.scala:284)
2021-05-03 20:40:35.086411500 	at controllers.HomeController.$anonfun$janico$1(HomeController.scala:291)
2021-05-03 20:40:35.086434500 	at scala.Function1.$anonfun$andThen$1(Function1.scala:57)
2021-05-03 20:40:35.087008500 	at play.api.mvc.ActionBuilderImpl.invokeBlock(Action.scala:488)
2021-05-03 20:40:35.087061500 	at play.api.mvc.ActionBuilderImpl.invokeBlock(Action.scala:486)
2021-05-03 20:40:35.089794500 	at play.api.mvc.ActionBuilder$$anon$10.apply(Action.scala:425)
2021-05-03 20:40:35.089821500 	at play.api.mvc.Action.$anonfun$apply$2(Action.scala:97)
2021-05-03 20:40:35.089885500 	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
2021-05-03 20:40:35.089911500 	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
2021-05-03 20:40:35.089934500 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
2021-05-03 20:40:35.089985500 	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
2021-05-03 20:40:35.090009500 	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
2021-05-03 20:40:35.090032500 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
2021-05-03 20:40:35.090056500 	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
2021-05-03 20:40:35.090084500 	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
2021-05-03 20:40:35.090108500 	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
2021-05-03 20:40:35.090131500 	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:44)
2021-05-03 20:40:35.090155500 	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
2021-05-03 20:40:35.090177500 	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
```

**Comment by zdavatz** [comment]
Maybe this helps: https://github.com/smarcu/door-sensor/issues/1#issuecomment-228543514

**Comment by zdavatz** [comment]
Testing like this: `curl -X POST -T 2021-04-30_091118 https://test.yopenedi.ch/janico -v`

**Comment by zdavatz** [comment]
`nmap --script ssl-enum-ciphers -p 443 www.google.com`

**Comment by zdavatz** [comment]
Der Email-Fetcher funktioniert auch nicht mehr: 
```
Reading from /home/zdavatz/software/yopenedi/java/./conf/email-credential.json
Exception in thread "main" javax.mail.MessagingException: No appropriate protocol (protocol is disabled or cipher suites are inappropriate);
  nested exception is:
	javax.net.ssl.SSLHandshakeException: No appropriate protocol (protocol is disabled or cipher suites are inappropriate)
	at com.sun.mail.imap.IMAPStore.protocolConnect(IMAPStore.java:670)
	at javax.mail.Service.connect(Service.java:295)
	at javax.mail.Service.connect(Service.java:176)
	at com.ywesee.java.yopenedi.emailfetcher.App.main(App.java:141)
Caused by: javax.net.ssl.SSLHandshakeException: No appropriate protocol (protocol is disabled or cipher suites are inappropriate)
	at sun.security.ssl.HandshakeContext.<init>(HandshakeContext.java:171)
	at sun.security.ssl.ClientHandshakeContext.<init>(ClientHandshakeContext.java:98)
	at sun.security.ssl.TransportContext.kickstart(TransportContext.java:220)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:428)
	at com.sun.mail.util.SocketFetcher.configureSSLSocket(SocketFetcher.java:527)
	at com.sun.mail.util.SocketFetcher.createSocket(SocketFetcher.java:332)
	at com.sun.mail.util.SocketFetcher.getSocket(SocketFetcher.java:234)
	at com.sun.mail.iap.Protocol.<init>(Protocol.java:116)
	at com.sun.mail.imap.protocol.IMAPProtocol.<init>(IMAPProtocol.java:115)
	at com.sun.mail.imap.IMAPStore.newIMAPProtocol(IMAPStore.java:685)
	at com.sun.mail.imap.IMAPStore.protocolConnect(IMAPStore.java:636)
	... 3 more
```

**Comment by zdavatz** [comment]
das hat nicht geholfen: `sudo update-ca-certificates --fresh`

**Comment by zdavatz** [comment]
Das hat geholfen: `sudo apt-get install openjdk-14-jre`

**Comment by zdavatz** [comment]
1. Ok, I solved the Email-Fetcher Problem [this way](https://mulesoftprm.force.com/s/article/TLS-1-1-or-1-0-connections-are-failing-with-javax-net-ssl-SSLHandshakeException-No-appropriate-protocol-protocol-is-disabled-or-cipher-suites-are-inappropriate-after-upgrading-OpenJDK-version).
2. Open this file: `/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/security/java.security`
3. removed `TLSv1, TLSv1.1`
4. Recompile Email-Fetcher with Java 8.
