### ISSUE TITLE
HTTP Post no longer working: Internal server error, for (POST) [/janico] ->

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/yopenedi#203]
1. Das klappt zur Zeit nicht: `curl -X POST -T 2021-04-29_090122 https://test.yopenedi.ch/janico -v`
2. Es gibt
```
2021-05-29 13:28:47.440983500 ! @7jpea4c89 - Internal server error, for (POST) [/janico] ->
2021-05-29 13:28:47.440983500  
2021-05-29 13:28:47.440983500 play.api.UnexpectedException: Unexpected exception[NullPointerException: null]
2021-05-29 13:28:47.440984500   at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:276)
2021-05-29 13:28:47.440984500   at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:203)
2021-05-29 13:28:47.441023500   at play.core.server.AkkaHttpServer$$anonfun$1.applyOrElse(AkkaHttpServer.scala:433)
2021-05-29 13:28:47.441023500   at play.core.server.AkkaHttpServer$$anonfun$1.applyOrElse(AkkaHttpServer.scala:431)
2021-05-29 13:28:47.441024500   at scala.concurrent.Future.$anonfun$recoverWith$1(Future.scala:417)
2021-05-29 13:28:47.441024500   at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
2021-05-29 13:28:47.441026500   at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
2021-05-29 13:28:47.441027500   at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
2021-05-29 13:28:47.441027500   at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
2021-05-29 13:28:47.441027500   at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
2021-05-29 13:28:47.441029500 Caused by: java.lang.NullPointerException: null
2021-05-29 13:28:47.441035500   at controllers.HomeController.janicoFn(HomeController.scala:224)
2021-05-29 13:28:47.441035500   at controllers.HomeController.$anonfun$janico$1(HomeController.scala:291)
2021-05-29 13:28:47.441036500   at scala.Function1.$anonfun$andThen$1(Function1.scala:57)
2021-05-29 13:28:47.441036500   at play.api.mvc.ActionBuilderImpl.invokeBlock(Action.scala:488)
2021-05-29 13:28:47.441036500   at play.api.mvc.ActionBuilderImpl.invokeBlock(Action.scala:486)
2021-05-29 13:28:47.441038500   at play.api.mvc.ActionBuilder$$anon$10.apply(Action.scala:425)
2021-05-29 13:28:47.441039500   at play.api.mvc.Action.$anonfun$apply$2(Action.scala:97)
2021-05-29 13:28:47.441039500   at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
2021-05-29 13:28:47.441039500   at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
2021-05-29 13:28:47.441040500   at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
```

**Comment by zdavatz** [comment]
Dieser Fehler geschieht, wenn man eine falsche Datei an die URL sendet.
