### ISSUE TITLE
Cannot read field "snd" because the return value is null

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/yopenedi#257]
1. This does not seem to work:
2. `curl -X POST -T 2024-03-22_151414 https://test.yopenedi.ch/janico -v`
3. Getting this error:
```
2024-03-22 18:25:30.926744500 ! @8513hojaf - Internal server error, for (POST) [/janico] ->
2024-03-22 18:25:30.926745500  
2024-03-22 18:25:30.926745500 play.api.UnexpectedException: Unexpected exception[NullPointerException: Cannot read field "snd" because the return value of "com.ywesee.java.yopenedi.converter.Converter.run(java.io.InputStream)" is null]
2024-03-22 18:25:30.926747500   at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:384)
2024-03-22 18:25:30.926782500   at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:267)
2024-03-22 18:25:30.926782500   at play.core.server.PekkoHttpServer$$anonfun$invokeAction$1$1.applyOrElse(PekkoHttpServer.scala:482)
2024-03-22 18:25:30.926783500   at play.core.server.PekkoHttpServer$$anonfun$invokeAction$1$1.applyOrElse(PekkoHttpServer.scala:474)
2024-03-22 18:25:30.926784500   at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:490)
2024-03-22 18:25:30.926788500   at org.apache.pekko.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:73)
2024-03-22 18:25:30.926789500   at org.apache.pekko.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:110)
2024-03-22 18:25:30.926790500   at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
2024-03-22 18:25:30.926800500   at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
2024-03-22 18:25:30.926801500   at org.apache.pekko.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:110)
2024-03-22 18:25:30.926801500 Caused by: java.lang.NullPointerException: Cannot read field "snd" because the return value of "com.ywesee.java.yopenedi.converter.Converter.run(java.io.InputStream)" is null
2024-03-22 18:25:30.926806500   at controllers.HomeController.janicoFn(HomeController.scala:376)
2024-03-22 18:25:30.926806500   at controllers.HomeController.$anonfun$janico$1(HomeController.scala:443)
2024-03-22 18:25:30.926807500   at scala.Function1.$anonfun$andThen$1(Function1.scala:87)
2024-03-22 18:25:30.926807500   at play.api.mvc.ActionBuilderImpl.invokeBlock(Action.scala:496)
2024-03-22 18:25:30.926811500   at play.api.mvc.ActionBuilderImpl.invokeBlock(Action.scala:494)
2024-03-22 18:25:30.926812500   at play.api.mvc.ActionBuilder$$anon$9.apply(Action.scala:434)
2024-03-22 18:25:30.926812500   at play.api.mvc.Action.$anonfun$apply$6(Action.scala:83)
2024-03-22 18:25:30.926813500   at play.api.mvc.BodyParser$.$anonfun$runParserThenInvokeAction$1(Action.scala:260)
2024-03-22 18:25:30.926813500   at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:470)
2024-03-22 18:25:30.926817500   at org.apache.pekko.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:73)
2024-03-22 18:35:15.352962500 [warn] o.a.p.a.ActorSystemImpl - Illegal request, responding with status '400 Bad Request': Unsupported HTTP method: HTTP method too long (started with 'MGLNDD_104.248.2') from 107.170.240.20:42488. Increase `pekko.http.server.parsing.max-method-length` to support HTTP methods with more characters.
```

**Comment by zdavatz** [comment]
[2024-03-22_151414.txt](https://github.com/zdavatz/yopenedi/files/14726531/2024-03-22_151414.txt)

**Comment by zdavatz** [comment]
This error happens because we the input is EDIFACT and not XML.
