### ISSUE TITLE
Sending Mail with 17.0.10 seems to throw an error

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/yopenedi#259]
1. In the Log I see:
2. Java 17.0.10
```
2024-03-26 09:32:28.319351500 Sending email from xmlconv@ywesee.com to DEJFROE1.DEFJC@ieeur.gxs.com
2024-03-26 09:32:28.379494500 javax.mail.MessagingException: Could not convert socket to TLS;
2024-03-26 09:32:28.379496500   nested exception is:
2024-03-26 09:32:28.379496500   javax.net.ssl.SSLHandshakeException: No appropriate protocol (protocol is disabled or cipher suites are inappropriate)
2024-03-26 09:32:28.379558500 javax.mail.MessagingException: Could not convert socket to TLS;
2024-03-26 09:32:28.379558500   nested exception is:
2024-03-26 09:32:28.379558500   javax.net.ssl.SSLHandshakeException: No appropriate protocol (protocol is disabled or cipher suites are inappropriate)
2024-03-26 09:32:28.379767500   at com.sun.mail.smtp.SMTPTransport.startTLS(SMTPTransport.java:1907)
2024-03-26 09:32:28.379783500   at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:666)
2024-03-26 09:32:28.379798500   at javax.mail.Service.connect(Service.java:317)
2024-03-26 09:32:28.379811500   at javax.mail.Service.connect(Service.java:176)
2024-03-26 09:32:28.379824500   at javax.mail.Service.connect(Service.java:125)
2024-03-26 09:32:28.379837500   at javax.mail.Transport.send0(Transport.java:253)
2024-03-26 09:32:28.379851500   at javax.mail.Transport.send(Transport.java:124)
2024-03-26 09:32:28.379865500   at com.ywesee.java.yopenedi.common.ResultDispatch.sendEmail(ResultDispatch.java:199)
2024-03-26 09:32:28.379878500   at com.ywesee.java.yopenedi.common.ResultDispatch.send(ResultDispatch.java:135)
2024-03-26 09:32:28.379892500   at com.ywesee.java.yopenedi.common.Config.dispatchResult(Config.java:119)
2024-03-26 09:32:28.379907500   at controllers.HomeController.janicoFn(HomeController.scala:436)
2024-03-26 09:32:28.379920500   at controllers.HomeController.$anonfun$janico$1(HomeController.scala:443)
2024-03-26 09:32:28.379935500   at scala.Function1.$anonfun$andThen$1(Function1.scala:87)
2024-03-26 09:32:28.380058500   at play.api.mvc.ActionBuilderImpl.invokeBlock(Action.scala:496)
```

**Comment by zdavatz** [comment]
1. I removed `TLSv1, TLSv1.1,`
2. from `/etc/java-17-openjdk/security/java.security`
3. according to https://superuser.com/questions/1649382/upgrade-from-openjdk-11-0-7-to-11-0-11-causes-sslhandshakeexception-no-appropri

**Comment by zdavatz** [comment]
[java.security.txt](https://github.com/zdavatz/yopenedi/files/14759711/java.security.txt)
