### ISSUE TITLE
Posting XML files results in an error

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/yopenedi#268]
1. Posting this XML file
2. Results in this error
```
@40000000666a95853afd304c ! @85o60g0ff - Internal server error, for (POST) [/janico] ->
@40000000666a95853afd304c
@40000000666a95853afd304c play.api.UnexpectedException: Unexpected exception[NullPointerException: Cannot read field "snd" because the return value of "com.ywesee.java.yopenedi.converter.Converter.run(java.io.InputStream)" is null]
@40000000666a95853afd3434       at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:384)
@40000000666a95853b0273f4       at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:267)
@40000000666a95853b0277dc       at play.core.server.PekkoHttpServer$$anonfun$invokeAction$1$1.applyOrElse(PekkoHttpServer.scala:482)
@40000000666a95853b027bc4       at play.core.server.PekkoHttpServer$$anonfun$invokeAction$1$1.applyOrElse(PekkoHttpServer.scala:474)
@40000000666a95853b027bc4       at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:490)
@40000000666a95853b028f4c       at org.apache.pekko.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:73)
@40000000666a95853b028f4c       at org.apache.pekko.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:110)
@40000000666a95853b029334       at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
@40000000666a95853b02b274       at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
@40000000666a95853b02b274       at org.apache.pekko.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:110)
@40000000666a95853b02b65c Caused by: java.lang.NullPointerException: Cannot read field "snd" because the return value of "com.ywesee.java.yopenedi.converter.Converter.run(java.io.InputStream)" is null
@40000000666a95853b02be2c       at controllers.HomeController.janicoFn(HomeController.scala:380)
@40000000666a95853b02c214       at controllers.HomeController.$anonfun$janico$1(HomeController.scala:447)
@40000000666a95853b02c214       at scala.Function1.$anonfun$andThen$1(Function1.scala:87)
@40000000666a95853b02c214       at play.api.mvc.ActionBuilderImpl.invokeBlock(Action.scala:496)
@40000000666a95853b030094       at play.api.mvc.ActionBuilderImpl.invokeBlock(Action.scala:494)
@40000000666a95853b030094       at play.api.mvc.ActionBuilder$$anon$9.apply(Action.scala:434)
@40000000666a95853b030094       at play.api.mvc.Action.$anonfun$apply$6(Action.scala:83)
@40000000666a95853b03047c       at play.api.mvc.BodyParser$.$anonfun$runParserThenInvokeAction$1(Action.scala:260)
@40000000666a95853b03047c       at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:470)
@40000000666a95853b030c4c       at org.apache.pekko.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:73)
```

**Comment by zdavatz** [comment]
![Screenshot 2024-06-14 at 16 08 10](https://github.com/zdavatz/yopenedi/assets/4953/b4efcdf7-22d3-4a75-9ad6-2124df7cf5a4)

**Comment by zdavatz** [comment]
Ich bin nicht sicher, gemäss #262, mussen wir Auftragsdatum, Lieferscheindatum, usw, hinzufügen, also ich <ORDER_DATE> und <DELIVERY_END_DATE> von OpenTrans XML suchen gehabt (#263). Aber in die INVOICE Datei, es gibt nur "<ORDER_DATE/>" und "<DELIVERY_END_DATE/>", es gibt kein Datum.

Ich habe es so machen: wenn es gibt <ORDER_DATE> in XML, wir werden es zu Edifact schreiben, ween es gibt keine, wir werden es nur weglassen.
