### ISSUE TITLE
controllers/routes has been compiled by a more recent version of the Java Runtime 

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/yopenedi#272]
1. Ist das ein Problem für uns?
2. 
```
2024-06-17 10:39:36.729909500 play.api.UnexpectedException: Unexpected exception[RuntimeException: java.lang.UnsupportedClassVersionError: controllers/routes has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 60.0]
2024-06-17 10:39:36.729941500   at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:384)
2024-06-17 10:39:36.729942500   at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:267)
2024-06-17 10:39:36.729945500   at play.core.server.PekkoHttpServer$$anonfun$invokeAction$1$1.applyOrElse(PekkoHttpServer.scala:482)
2024-06-17 10:39:36.729946500   at play.core.server.PekkoHttpServer$$anonfun$invokeAction$1$1.applyOrElse(PekkoHttpServer.scala:474)
2024-06-17 10:39:36.729946500   at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:490)
2024-06-17 10:39:36.729964500   at org.apache.pekko.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:73)
2024-06-17 10:39:36.729980500   at org.apache.pekko.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:110)
2024-06-17 10:39:36.729987500   at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
2024-06-17 10:39:36.729988500   at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
2024-06-17 10:39:36.729988500   at org.apache.pekko.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:110)
2024-06-17 10:39:36.729989500 Caused by: java.lang.RuntimeException: java.lang.UnsupportedClassVersionError: controllers/routes has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 60.0
2024-06-17 10:39:36.729992500   at play.api.mvc.ActionBuilder$$anon$9.apply(Action.scala:439)
2024-06-17 10:39:36.729992500   at play.api.mvc.Action.$anonfun$apply$6(Action.scala:83)
2024-06-17 10:39:36.729992500   at play.api.mvc.BodyParser$.$anonfun$runParserThenInvokeAction$1(Action.scala:260)
2024-06-17 10:39:36.729995500   at play.api.libs.streams.StrictAccumulator.$anonfun$mapFuture$4(Accumulator.scala:167)
2024-06-17 10:39:36.729995500   at scala.util.Try$.apply(Try.scala:217)
2024-06-17 10:39:36.729995500   at play.api.libs.streams.StrictAccumulator.$anonfun$mapFuture$3(Accumulator.scala:167)
2024-06-17 10:39:36.729996500   at scala.Function1.$anonfun$andThen$1(Function1.scala:87)
2024-06-17 10:39:36.730001500   at scala.Function1.$anonfun$andThen$1(Function1.scala:87)
2024-06-17 10:39:36.730002500   at scala.Function1.$anonfun$andThen$1(Function1.scala:87)
2024-06-17 10:39:36.730002500   at play.api.libs.streams.StrictAccumulator.run(Accumulator.scala:198)
2024-06-17 10:39:36.730002500 Caused by: java.lang.UnsupportedClassVersionError: controllers/routes has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 60.0
2024-06-17 10:39:36.730005500   at views.html.main$.apply(main.template.scala:37)
2024-06-17 10:39:36.730005500   at views.html.index$.apply(index.template.scala:27)
2024-06-17 10:39:36.730006500   at controllers.HomeController.$anonfun$index$1(HomeController.scala:46)
2024-06-17 10:39:36.730008500   at scala.Function1.$anonfun$andThen$1(Function1.scala:87)
2024-06-17 10:39:36.730008500   at play.api.mvc.ActionBuilderImpl.invokeBlock(Action.scala:496)
2024-06-17 10:39:36.730009500   at play.api.mvc.ActionBuilderImpl.invokeBlock(Action.scala:494)
2024-06-17 10:39:36.730009500   at play.api.mvc.ActionBuilder$$anon$9.apply(Action.scala:434)
2024-06-17 10:39:36.730009500   at play.api.mvc.Action.$anonfun$apply$6(Action.scala:83)
2024-06-17 10:39:36.730012500   at play.api.mvc.BodyParser$.$anonfun$runParserThenInvokeAction$1(Action.scala:260)
2024-06-17 10:39:36.730012500   at play.api.libs.streams.StrictAccumulator.$anonfun$mapFuture$4(Accumulator.scala:167)
```

**Comment by zdavatz** [comment]
Going back to Java 17
