### ISSUE TITLE
OBETA EDIFACT files give an error

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/yopenedi#63]
[143736_08072020.txt](https://github.com/zdavatz/yopenedi/files/4890968/143736_08072020.txt)
[143721_08072020.txt](https://github.com/zdavatz/yopenedi/files/4890969/143721_08072020.txt)
[143651_08072020.txt](https://github.com/zdavatz/yopenedi/files/4890970/143651_08072020.txt)
[143606_08072020.txt](https://github.com/zdavatz/yopenedi/files/4890971/143606_08072020.txt)

**Comment by zdavatz** [comment]
java
```
Exception in thread "main" java.lang.NullPointerException
        at java.text.SimpleDateFormat.parse(SimpleDateFormat.java:1439)
        at java.text.DateFormat.parse(DateFormat.java:364)
        at com.ywesee.java.yopenedi.converter.Converter.dateStringToISOString(Converter.java:278)
        at com.ywesee.java.yopenedi.converter.Converter.orderToOpenTrans(Converter.java:24)
        at com.ywesee.java.yopenedi.cli.App.edifactToOpenTrans(App.java:164)
        at com.ywesee.java.yopenedi.cli.App.main(App.java:144)
```
meteor
```
143736_08072020.xml:11: parser error : Opening and ending tag mismatch: ORDER line 1 and FTX
ERY_END_DATE>2020-07-08</DELIVERY_END_DATE></ORDER_ITEM></ORDER_ITEM_LIST></FTX>
                                                                               ^
143736_08072020.xml:11: parser error : Extra content at the end of the document
ERY_END_DATE>2020-07-08</DELIVERY_END_DATE></ORDER_ITEM></ORDER_ITEM_LIST></FTX>
```

**Comment by zdavatz** [comment]
Meteor 81b500d6946a3762d24542359d3e21ca8ad1db87

**Comment by zdavatz** [comment]
Java: 14c59b8a9e54df33db7d0b598a13f565851244d5
