### ISSUE TITLE
"dist" Befehl geht nicht für Activator: Not a valid command: dist (similar: set, iflast, last)

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/yopenedi#68]
```
zdavatz@yopenedi-test:~/software/yopenedi/java/server$ activator
[info] Loading settings for project server-build from plugins.sbt ...
[info] Loading project definition from /home/zdavatz/software/yopenedi/java/server/project
[info] Set current project to server (in build file:/home/zdavatz/software/yopenedi/java/server/)
[info] sbt server started at local:///home/zdavatz/.sbt/1.0/server/3c97f0a7f2d13bcbca8b/sock
sbt:server> dist
[error] Not a valid command: dist (similar: set, iflast, last)
[error] Not a valid project ID: dist
[error] Expected ':'
[error] Not a valid key: dist (similar: bgList, test, history)
[error] dist
[error]     ^
sbt:server>
```

**Comment by zdavatz** [comment]
https://www.playframework.com/documentation/2.8.x/Deploying

**Comment by zdavatz** [comment]
das geht: 
```
cd java
./gradlew server:dist`
```
Die `.zip` Datei ist dann in: `java/server/build/distributions`

**Comment by zdavatz** [comment]
jetzt müssen wir noch das `Application Secret` setzen oder deaktiveren:

```
zdavatz@yopenedi-test:/var/www/test.yopenedi.ch/playBinary/bin$ ./playBinary
log4j:WARN No appenders could be found for logger (org.jboss.logging).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Oops, cannot start the server.
Configuration error: Configuration error[
The application secret has not been set, and we are in prod mode. Your application is not secure.
To set the application secret, please read http://playframework.com/documentation/latest/ApplicationSecret
          ]
	at play.api.Configuration$.configError(Configuration.scala:168)
	at play.api.Configuration.reportError(Configuration.scala:1015)
	at play.api.http.HttpConfiguration$.getSecretConfiguration(HttpConfiguration.scala:265)
	at play.api.http.HttpConfiguration$.fromConfiguration(HttpConfiguration.scala:249)
```

**Comment by zdavatz** [comment]
das geht: `JAVA_OPTS="-Dplay.http.secret.key='12344356788'" ./playBinary`

**Comment by zdavatz** [comment]
das geht jetzt auch `make dist-server` mit Commit f90c9130df164d01eb9648bf32b076e9570c9e81

**Comment by zdavatz** [comment]
```
cd /home/zdavatz/software/yopenedi/java
make dist-server
rm -r /var/www/test.yopenedi.ch/playBinary
cp /home/zdavatz/software/yopenedi/java/server/build/distributions/playBinary.zip /var/www/test.yopenedi.ch/
cd /var/www/test.yopenedi.ch/
unzip playBinary.zip
rm playBinary.zip
```
